# _config.yml
url: "https://dugijan.ir"       # For production
baseurl: ""                        # Leave empty or use "/repo" for project sites

collections:
  products:
    output: true
    permalink: /products/:slug/
    
plugins:
  - jekyll-redirect-from