url: "https://dugijan.ir"
mobile : "09146853523" 

permalink: /:year/:month/:day/:title/

collections:
  products:
    output: true
    permalink: /products/:slug/
    
plugins:
  - jekyll-redirect-from