url: "https://dugijan.ir"
mobile : "09146853523"
email : "info@dugijan.ir"
address : آذربایجانشرقی - شهر تبریز - مرکز دوگیجان
permalink: pretty  # This removes .html from URLs

collections:
  products:
    output: true
    permalink: /products/:slug/
  posts:
    permalink: /:title/  # No .html for posts
    
plugins:
  - jekyll-redirect-from
