url: "https://dugijan.ir"
mobile : "09146853523"
email : "info@dugijan.ir"
address : آذربایجانشرقی - شهر تبریز - مرکز دوگیجان

permalink: /:year/:month/:day/:title/
include: [404.html] 

collections:
  products:
    output: true
    permalink: /products/:slug/
    
plugins:
  - jekyll-redirect-from